### ISSUE TITLE
login blocked by CORS policy

### ISSUE THREAD

**Issue by lukehatfield** [OblikStudio/kirby-memsource#10]
Hi, I can't login with my Memsource credentials to this plugin in the panel. I keep getting the "Error: Network Error" which shows up in my web inspector console as a CORS policy: No 'Access-Control-Allow-Origin' header is present on the request resource. What am I doing wrong?

**Comment by hdodov** [comment]
I'm experiencing the same issue on our live site. Surprisingly, everything works fine locally. I opened a ticket to Memsource asking how I should handle it. Sorry for the inconvenience and thanks for reporting!
